// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP17WJzHT0nKON5eMrNrSWkSmm59cDUX8',
    appId: '1:97791239748:web:1cb653972414bfbdb6fe11',
    messagingSenderId: '97791239748',
    projectId: 'blinkit-assignment',
    authDomain: 'blinkit-assignment.firebaseapp.com',
    storageBucket: 'blinkit-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa7coaQlbKDGTzmygqo0rXZr_lehFy5to',
    appId: '1:97791239748:android:408bc641272ecd3ab6fe11',
    messagingSenderId: '97791239748',
    projectId: 'blinkit-assignment',
    storageBucket: 'blinkit-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa1wVwq0xM61KhX5KDv8qa9cbSkvH3SOQ',
    appId: '1:97791239748:ios:460ad4e2141b577eb6fe11',
    messagingSenderId: '97791239748',
    projectId: 'blinkit-assignment',
    storageBucket: 'blinkit-assignment.appspot.com',
    iosBundleId: 'com.example.blinkitAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa1wVwq0xM61KhX5KDv8qa9cbSkvH3SOQ',
    appId: '1:97791239748:ios:b29a947c1345d090b6fe11',
    messagingSenderId: '97791239748',
    projectId: 'blinkit-assignment',
    storageBucket: 'blinkit-assignment.appspot.com',
    iosBundleId: 'com.example.blinkitAssignment.RunnerTests',
  );
}
